# Generated by Django 4.2.7 on 2023-12-30 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orgs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_settings', '__first__'),
        ('custom_auth', '0003_alter_useraccount_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('note', models.TextField(max_length=1000, null=True, verbose_name='note')),
                ('expected_date', models.DateField(null=True, verbose_name='expected date')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=orgs.models.file_location)),
                ('created_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='created date')),
                ('employee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_employee', to='custom_auth.useraccount', verbose_name='employee')),
                ('order_stage', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ord_stage', to='app_settings.orderstage', verbose_name='order stage')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_settings.orderstatus', verbose_name='order status')),
                ('org_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_settings.organizationtype', verbose_name='organization type')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizationVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_state', models.IntegerField(choices=[(1, 'agreed'), (2, 'disagreed')], default=0, verbose_name='visit state')),
                ('visit_note', models.CharField(blank=True, max_length=100, verbose_name='visit note')),
                ('is_reviewed', models.IntegerField(choices=[(0, 'no'), (1, 'yes')], default=0, verbose_name='is reviewed')),
                ('review_note', models.CharField(blank=True, max_length=100, verbose_name='review note')),
                ('created_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='created date')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization', verbose_name='organization')),
                ('reviewer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_reviewer', to='custom_auth.useraccount', verbose_name='reviewer')),
                ('service_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_settings.servicesection', verbose_name='service section')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_settings.servicetype', verbose_name='service type')),
                ('visitor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_visitor', to='custom_auth.useraccount', verbose_name='visitor')),
            ],
            options={
                'verbose_name': 'Organization Visit',
                'verbose_name_plural': 'Organization Visits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visited', models.IntegerField(default=0, verbose_name='is visited')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization', verbose_name='organization')),
                ('service_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_settings.servicesection', verbose_name='service section')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_settings.servicetype', verbose_name='service type')),
            ],
            options={
                'verbose_name': 'Organization Service',
                'verbose_name_plural': 'Organization Services',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizationEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('mobile', models.CharField(blank=True, max_length=100, verbose_name='mobile number')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization', verbose_name='organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_settings.employeerole', verbose_name='employee role')),
            ],
            options={
                'verbose_name': 'Organization Employee',
                'verbose_name_plural': 'Organization Employees',
                'managed': True,
            },
        ),
    ]
