# Generated by Django 4.2.7 on 2023-12-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Employee Role',
                'verbose_name_plural': 'Employee Role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Statuses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('note', models.CharField(max_length=1000, null=True, verbose_name='note')),
                ('expected_date', models.DateField(null=True, verbose_name='expected date')),
                ('employee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_employee', to='custom_auth.useraccount', verbose_name='employee')),
                ('engineer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_engineer', to='custom_auth.useraccount', verbose_name='engineer')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orgs.orderstatus', verbose_name='order status')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Organization Type',
                'verbose_name_plural': 'Organization Type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Service Section',
                'verbose_name_plural': 'Service Section',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization', verbose_name='organization')),
                ('service_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.servicesection', verbose_name='service section')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.servicetype', verbose_name='service type')),
            ],
            options={
                'verbose_name': 'Organization Service',
                'verbose_name_plural': 'Organization Services',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizationEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('mobile', models.CharField(blank=True, max_length=100, verbose_name='mobile number')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization', verbose_name='organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orgs.employeerole', verbose_name='employee role')),
            ],
            options={
                'verbose_name': 'Organization Employee',
                'verbose_name_plural': 'Organization Employees',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orgs.organizationtype', verbose_name='organization type'),
        ),
    ]
