# Generated by Django 4.2.7 on 2023-12-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_useraccount_email_and_more'),
        ('app_settings', '0001_initial'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_employee', to='custom_auth.useraccount', verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='order_stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ord_stage', to='app_settings.orderstage', verbose_name='order stage'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='order_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_settings.orderstatus', verbose_name='order status'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_settings.organizationtype', verbose_name='organization type'),
        ),
    ]
