# Generated by Django 4.2.7 on 2023-12-12 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_orderstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='order_stage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ord_stage', to='orgs.orderstage', verbose_name='order stage'),
        ),
    ]
