# Generated by Django 4.2.7 on 2023-12-30 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_alter_organization_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationemployee',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='created date'),
        ),
        migrations.AddField(
            model_name='organizationservice',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='created date'),
        ),
    ]
