# Generated by Django 4.2.7 on 2023-12-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_organization_order_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='note',
            field=models.TextField(max_length=1000, null=True, verbose_name='note'),
        ),
    ]
