# Generated by Django 4.2.7 on 2023-12-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_organizationemployee_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationservice',
            name='is_visited',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], default=0, verbose_name='is visited'),
        ),
    ]
