# Generated by Django 4.2.7 on 2023-12-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_alter_organization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='order_status',
            field=models.IntegerField(choices=[('1', 'جديد'), ('2', 'تحديد تاريخ'), ('2', 'محتمل')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('1', 'برج'), ('2', 'مركز تجاري')], default='1', max_length=10),
            preserve_default=False,
        ),
    ]
