# Generated by Django 4.2.7 on 2024-01-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_alter_servicesection_section_manager'),
        ('orgs', '0004_alter_organizationservice_is_visited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': True, 'ordering': ['expected_date'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterField(
            model_name='organizationvisit',
            name='visit_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_settings.visitstatus', verbose_name='visit state'),
        ),
    ]
