# Generated by Django 4.2.7 on 2023-12-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_alter_organization_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='admin_note',
            field=models.TextField(max_length=1000, null=True, verbose_name='admin note'),
        ),
        migrations.AddField(
            model_name='organization',
            name='engineer_note',
            field=models.TextField(max_length=1000, null=True, verbose_name='engineer note'),
        ),
    ]
