# Generated by Django 4.2.7 on 2023-12-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_organizationtype_organization_note_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationEmployee',
        ),
        migrations.RemoveField(
            model_name='organizationservice',
            name='service_section',
        ),
        migrations.RemoveField(
            model_name='organizationservice',
            name='service_type',
        ),
        migrations.DeleteModel(
            name='OrganizationType',
        ),
        migrations.AlterField(
            model_name='organization',
            name='order_status',
            field=models.IntegerField(choices=[('1', 'جديد'), ('2', 'تحديد تاريخ'), ('3', 'محتمل')]),
        ),
        migrations.DeleteModel(
            name='OrganizationService',
        ),
        migrations.DeleteModel(
            name='ServiceSection',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
