# Generated by Django 4.2.7 on 2023-12-18 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_useraccount_second_name'),
        ('orgs', '0005_organization_admin_note_organization_engineer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesection',
            name='section_manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_manager', to='custom_auth.useraccount', verbose_name='section manager'),
        ),
        migrations.CreateModel(
            name='ServiceSectionEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_auth.useraccount', verbose_name='section engineer')),
                ('service_section', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.servicesection', verbose_name='service section')),
                ('service_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.servicetype', verbose_name='service type')),
            ],
            options={
                'verbose_name': 'Service Section',
                'verbose_name_plural': 'Service Section',
                'managed': True,
            },
        ),
    ]
