# Generated by Django 4.2.7 on 2023-12-01 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_delete_organizationemployee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_section', models.IntegerField(choices=[('1', 'امن'), ('2', 'مصاعد')])),
                ('service_type', models.IntegerField(choices=[('1', 'مالك'), ('2', 'موظف'), ('3', 'مدير')])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('role', models.IntegerField(choices=[('1', 'مالك'), ('2', 'موظف'), ('3', 'مدير')])),
                ('mobile', models.CharField(blank=True, max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
            ],
        ),
    ]
