# Generated by Django 4.2.7 on 2024-01-09 15:47

from django.db import migrations, models
import orgs.models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=orgs.models.file_location, verbose_name='image url'),
        ),
    ]
