# Generated by Django 4.2.7 on 2024-01-13 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orgs.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_alter_servicesection_section_manager'),
        ('custom_auth', '0004_alter_useraccount_last_name'),
        ('orgs', '0006_alter_organization_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=orgs.models.image_location, verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='organizationvisit',
            name='reviewer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_reviewer', to='custom_auth.useraccount', verbose_name='reviewer'),
        ),
        migrations.AlterField(
            model_name='organizationvisit',
            name='visit_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_settings.visitstatus', verbose_name='visit state'),
        ),
        migrations.AlterField(
            model_name='organizationvisit',
            name='visitor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_visitor', to='custom_auth.useraccount', verbose_name='visitor'),
        ),
        migrations.CreateModel(
            name='VisitTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='started at')),
                ('finished_at', models.DateField(null=True, verbose_name='finished at')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='note')),
                ('created_at', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='created at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization', verbose_name='organization')),
                ('task_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_settings.visitstatus', verbose_name='task state')),
                ('visitor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_visitor', to='custom_auth.useraccount', verbose_name='visitor')),
            ],
            options={
                'verbose_name': 'Visit Task',
                'verbose_name_plural': 'Visit Tasks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=orgs.models.file_location, verbose_name='file url')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='file description')),
                ('created_at', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_auth.useraccount', verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'Organization File',
                'verbose_name_plural': 'Organization Files',
                'managed': True,
            },
        ),
    ]
