# Generated by Django 4.2.7 on 2023-12-19 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_useraccount_email_and_more'),
        ('orgs', '0007_rename_engineer_servicesectionemployee_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesectionemployee',
            options={'managed': True, 'verbose_name': 'Service Section Employee', 'verbose_name_plural': 'Service Section Employees'},
        ),
        migrations.AddField(
            model_name='organization',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_manager', to='custom_auth.useraccount', verbose_name='manager'),
        ),
    ]
