# Generated by Django 4.2.7 on 2024-01-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_alter_organization_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationfile',
            name='description',
            field=models.CharField(max_length=100, verbose_name='file description'),
        ),
    ]
