# Generated by Django 4.2.7 on 2023-12-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_employeerole_orderstatus_servicesection_servicetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeRole',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='OrganizationType',
        ),
        migrations.DeleteModel(
            name='ServiceSection',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
