# Generated by Django 4.2.7 on 2024-01-13 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_alter_servicesection_section_manager'),
        ('orgs', '0008_alter_organizationfile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visittask',
            name='task_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_settings.visitstatus', verbose_name='task state'),
        ),
    ]
