# Generated by Django 4.2.7 on 2023-12-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_useraccount_email_and_more'),
        ('orgs', '0008_alter_servicesectionemployee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_note', models.CharField(blank=True, max_length=100, verbose_name='visit note')),
                ('visit_state', models.CharField(blank=True, max_length=100, verbose_name='visit state')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization', verbose_name='organization')),
                ('service_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.servicesection', verbose_name='service section')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.servicetype', verbose_name='service type')),
                ('visitor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_visitor', to='custom_auth.useraccount', verbose_name='visitor')),
            ],
        ),
    ]
