# Generated by Django 4.2.7 on 2023-12-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_organizationvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Visit Status',
                'verbose_name_plural': 'Visit Statuses',
                'managed': True,
            },
        ),
    ]
