# Generated by Django 4.2.7 on 2024-01-27 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0005_taskstatus'),
        ('orgs', '0009_alter_visittask_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visittask',
            name='task_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_settings.taskstatus', verbose_name='task state'),
        ),
    ]
