# Generated by Django 4.2.7 on 2023-12-05 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_employeerole_orderstatus_organizationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orgs.organizationtype'),
        ),
    ]
