# Generated by Django 4.2.7 on 2023-12-05 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_alter_organization_org_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orgs.orderstatus'),
        ),
        migrations.AlterField(
            model_name='organizationemployee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orgs.employeerole'),
        ),
        migrations.AlterField(
            model_name='organizationservice',
            name='service_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.servicesection'),
        ),
        migrations.AlterField(
            model_name='organizationservice',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.servicetype'),
        ),
    ]
