# Generated by Django 4.2.7 on 2023-12-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_useraccount_email_and_more'),
        ('orgs', '0011_organizationvisit_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationvisit',
            name='review_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='review note'),
        ),
        migrations.AddField(
            model_name='organizationvisit',
            name='reviewer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_reviewer', to='custom_auth.useraccount', verbose_name='reviewer'),
        ),
        migrations.AlterField(
            model_name='organizationvisit',
            name='is_reviewed',
            field=models.IntegerField(default=0, verbose_name='is reviewed'),
        ),
    ]
