# Generated by Django 4.2.7 on 2024-02-04 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_alter_useraccount_last_name'),
        ('orgs', '0011_organizationemployee_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationservice',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_auth.useraccount', verbose_name='created by'),
        ),
    ]
