# Generated by Django 4.2.7 on 2023-12-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_alter_organization_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='expected_date',
            field=models.DateField(null=True),
        ),
    ]
