# Generated by Django 4.2.7 on 2023-12-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_alter_organizationvisit_is_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationvisit',
            name='is_reviewed',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], default=0, verbose_name='is reviewed'),
        ),
        migrations.AlterField(
            model_name='organizationvisit',
            name='visit_state',
            field=models.IntegerField(choices=[(0, 'agreed'), (1, 'disagreed')], default=0, verbose_name='visit state'),
        ),
    ]
