# Generated by Django 4.2.7 on 2023-12-07 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_organization_expected_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationservice',
            old_name='service_section',
            new_name='servicesection',
        ),
        migrations.RenameField(
            model_name='organizationservice',
            old_name='service_type',
            new_name='servicetype',
        ),
    ]
