# Generated by Django 4.2.7 on 2023-12-08 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0014_rename_service_section_organizationservice_servicesection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationemployee',
            old_name='role',
            new_name='employeerole',
        ),
    ]
