# Generated by Django 4.2.7 on 2023-12-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0014_alter_organizationvisit_is_reviewed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationvisit',
            options={'managed': True, 'verbose_name': 'Organization Visit', 'verbose_name_plural': 'Organization Visits'},
        ),
        migrations.AddField(
            model_name='organizationservice',
            name='is_visited',
            field=models.IntegerField(default=0, verbose_name='is visited'),
        ),
        migrations.AlterField(
            model_name='organizationvisit',
            name='visit_state',
            field=models.IntegerField(choices=[(1, 'agreed'), (2, 'disagreed')], default=0, verbose_name='visit state'),
        ),
    ]
