# Generated by Django 4.2.7 on 2023-12-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_rename_role_organizationemployee_employeerole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationemployee',
            old_name='employeerole',
            new_name='role',
        ),
    ]
