# Generated by Django 4.2.7 on 2023-12-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_rename_employeerole_organizationemployee_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationservice',
            old_name='servicesection',
            new_name='service_section',
        ),
        migrations.RenameField(
            model_name='organizationservice',
            old_name='servicetype',
            new_name='service_type',
        ),
    ]
