# Generated by Django 4.2.7 on 2023-12-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_organization_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='manager',
        ),
    ]
