# Generated by Django 4.2.7 on 2023-12-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0017_remove_organization_engineer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='engineer_note',
        ),
        migrations.AlterField(
            model_name='organization',
            name='admin_note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='admin note'),
        ),
    ]
