# Generated by Django 4.2.7 on 2023-12-30 10:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0018_remove_organization_engineer_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 30, 13, 29, 37, 869141), null=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='order_stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ord_stage', to='orgs.orderstage', verbose_name='order stage'),
        ),
    ]
