# Generated by Django 4.2.7 on 2023-12-30 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0019_organization_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='created date'),
        ),
    ]
