# Generated by Django 4.2.7 on 2023-12-30 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0021_remove_organization_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationvisit',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='created date'),
        ),
    ]
