# Generated by Django 4.2.7 on 2023-12-11 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0017_rename_servicesection_organizationservice_service_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='خط الطول')),
                ('latitude', models.FloatField(verbose_name='خط العرض')),
                ('country_name', models.CharField(max_length=100, verbose_name='الدولة')),
                ('locality', models.CharField(max_length=200, verbose_name='المنطقة')),
                ('address', models.CharField(max_length=1000, verbose_name='العنوان')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orgs.organization')),
            ],
        ),
    ]
