# Generated by Django 4.2.7 on 2023-12-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='user type name')),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('second_name', models.CharField(max_length=100, verbose_name='second name')),
                ('third_name', models.CharField(max_length=100, verbose_name='third name')),
                ('fourth_name', models.CharField(max_length=100, verbose_name='fourth name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('mobile', models.CharField(max_length=100, verbose_name='mobile')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='custom_auth.usertype', verbose_name='user type')),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Account',
                'managed': True,
            },
        ),
    ]
