# Generated by Django 4.2.7 on 2023-12-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_useraccount_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='last name'),
        ),
    ]
