# Generated by Django 4.2.7 on 2023-12-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0003_alter_useraccount_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Employee Role',
                'verbose_name_plural': 'Employee Role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Order Stage',
                'verbose_name_plural': 'Order Stages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Statuses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Organization Type',
                'verbose_name_plural': 'Organization Type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('section_manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_manager', to='custom_auth.useraccount', verbose_name='section manager')),
            ],
            options={
                'verbose_name': 'Service Section',
                'verbose_name_plural': 'Service Section',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VisitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Visit Status',
                'verbose_name_plural': 'Visit Statuses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceSectionEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_auth.useraccount', verbose_name='section engineer')),
                ('service_section', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_settings.servicesection', verbose_name='service section')),
                ('service_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_settings.servicetype', verbose_name='service type')),
            ],
            options={
                'verbose_name': 'Service Section Employee',
                'verbose_name_plural': 'Service Section Employees',
                'managed': True,
            },
        ),
    ]
