# Generated by Django 4.2.7 on 2023-12-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_contract', models.IntegerField(max_length=100, verbose_name='days before contract')),
            ],
            options={
                'verbose_name': 'Project Setting',
                'verbose_name_plural': 'Project Settings',
                'managed': True,
            },
        ),
    ]
