# Generated by Django 4.2.7 on 2023-12-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_projectsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsetting',
            name='days_before_contract',
            field=models.IntegerField(verbose_name='days before contract'),
        ),
    ]
