# Generated by Django 4.2.7 on 2023-12-31 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_alter_useraccount_last_name'),
        ('app_settings', '0003_alter_projectsetting_days_before_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesection',
            name='section_manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_manager', to='custom_auth.useraccount', verbose_name='section manager'),
        ),
    ]
