# Generated by Django 4.2.7 on 2024-01-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_alter_servicesection_section_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Task Status',
                'verbose_name_plural': 'Task Statuses',
                'managed': True,
            },
        ),
    ]
